kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: coffee-shop-{{ .newVersion }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: coffee-shop
        version: {{ .newVersion }}
    spec:
      containers:
      - name: coffee-shop
        image: sdaschner/coffee-shop:istio-ee-{{ .image }}
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "curl -f localhost:9080/"
        readinessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "curl -s http://localhost:9080/health | grep -q coffee-shop"
        ports:
        - containerPort: 9080
      restartPolicy: Always
---
