kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: coffee-shop-{{ .newVersion }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: coffee-shop
        version: {{ .newVersion }}
    spec:
      containers:
      - name: coffee-shop
        image: sdaschner/coffee-shop:bulletproof-ee-{{ .image }}
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "curl -f localhost:9080/"
          initialDelaySeconds: 10
        readinessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "curl -f localhost:9080/coffee-shop/resources/health"
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 2
        ports:
        - containerPort: 9080
      restartPolicy: Always
---
